pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
        mavenLocal()
    }
}
rootProject.name = "kvision"

include(
    "kvision-modules:kvision-common-annotations",
    "kvision-modules:kvision-common-types",
    "kvision-modules:kvision-common-remote",
    "kvision-modules:kvision-bootstrap",
    "kvision-modules:kvision-bootstrap-icons",
    "kvision-modules:kvision-bootstrap-upload",
    "kvision-modules:kvision-onsenui",
    "kvision-modules:kvision-chart",
    "kvision-modules:kvision-cordova",
    "kvision-modules:kvision-datetime",
    "kvision-modules:kvision-electron",
    "kvision-modules:kvision-fontawesome",
    "kvision-modules:kvision-handlebars",
    "kvision-modules:kvision-i18n",
    "kvision-modules:kvision-imask",
    "kvision-modules:kvision-jquery",
    "kvision-modules:kvision-maps",
    "kvision-modules:kvision-pace",
    "kvision-modules:kvision-print",
    "kvision-modules:kvision-react",
    "kvision-modules:kvision-redux",
    "kvision-modules:kvision-redux-kotlin",
    "kvision-modules:kvision-rest",
    "kvision-modules:kvision-richtext",
    "kvision-modules:kvision-routing-navigo",
    "kvision-modules:kvision-routing-navigo-ng",
    "kvision-modules:kvision-select-remote",
    "kvision-modules:kvision-state",
    "kvision-modules:kvision-state-flow",
    "kvision-modules:kvision-tabulator",
    "kvision-modules:kvision-tabulator-remote",
    "kvision-modules:kvision-toastify",
    "kvision-modules:kvision-tom-select",
    "kvision-modules:kvision-tom-select-remote",
    "kvision-modules:kvision-server-javalin",
    "kvision-modules:kvision-server-jooby",
    "kvision-modules:kvision-server-ktor",
    "kvision-modules:kvision-server-ktor-koin",
    "kvision-modules:kvision-server-spring-boot",
    "kvision-modules:kvision-server-vertx",
    "kvision-modules:kvision-server-micronaut",
    "kvision-modules:kvision-testutils",
    "kvision-tools:kvision-gradle-plugin",
    "kvision-tools:kvision-ksp-processor",
    "kvision-assets",
)
