./gradlew stop
rm -rf build/bundle
rm -rf build/js
rm -rf build/js-tests
rm -rf build/reports
rm -rf build/resources
rm -rf build/tmp
rm -rf build/logs
rm -rf build/package.json
rm -rf build/package-lock.json
rm -rf build/.modules.with.kotlin.txt
rm -rf build/.modules.with.types.txt
rm -rf build/.npmrc
rm -rf build/.unpack.txt
rm -rf build/kotlin
rm -rf build/kotlin-build
rm -rf build/*.js
rm -rf build/node_modules/kotlin
rm -rf build/node_modules/kotlin-test
rm -rf build/node_modules/kvision
rm -rf build/node_modules/navigo-kotlin
rm -rf build/node_modules/jquery-kotlin
rm -rf build/node_modules/snabbdom-kotlin
rm -rf build/node_modules/kotlin-observable-js
rm -rf build/node_modules_imported
./gradlew -t run
